In [17]:
consumer_key = 'mvSJf2Niz6xRp0H66NBuDlsMb'
consumer_secret = 'GzMTCBb58sTLkIIdo4vECSJ6gi8cpgRCn3HFauuIOhR7wSRFTk'
access_token = '942299450-gkv8h9l4SNw9zLSMLK8hu6edi0hd36ej9X4WytH8'
access_token_secret = 'slpowSOoRxqvUHFngcGKeg7ryWce4PGudhILr5eqj8YoV'

In [18]:
import tweepy

In [19]:
import json
import pandas as pd

In [46]:
twitterLinks = pd.read_csv('base_data/twitterURLS.txt', header=None)

In [47]:
twitterLinks = twitterLinks.rename(columns={0: "url"})
twitterLinks['handle'] = twitterLinks.url.map(lambda x: x.split('/')[-1])
twitterLinks

                                       url           handle
0          https://twitter.com/chrishughes      chrishughes
1              http://twitter.com/mpclark3         mpclark3
2             http://twitter.com/peterpham        peterpham
3         http://twitter.com/bigchiefalice    bigchiefalice
4           http://twitter.com/jason_rubin      jason_rubin
5                   http://twitter.com/gmc              gmc
6                   http://twitter.com/biz              biz
7             http://twitter.com/tripadler        tripadler
8               https://twitter.com/pierre           pierre
9               https://twitter.com/swamus           swamus
10              http://twitter.com/barneyp          barneyp
11               http://twitter.com/thione           thione
12            http://twitter.com/tedmurphy        tedmurphy
13                http://twitter.com/Jason            Jason
14             http://twitter.com/todddowl         todddowl
15               http://twitter.com/sanity           sanity
16              http://twitter.com/aldamiz          aldamiz
17                http://twitter.com/ginab            ginab
18          http://twitter.com/Chad_Hurley      Chad_Hurley
19            http://twitter.com/stevechen        stevechen
20               http://twitter.com/eshear           eshear
21               https://twitter.com/kvogt            kvogt
22           http://twitter.com/bhunstable       bhunstable
23           http://twitter.com/cwalker123       cwalker123
24      https://twitter.com/jesslivingston   jesslivingston
25        http://twitter.com/blakewilliams    blakewilliams
26             http://twitter.com/betashop         betashop
27               http://twitter.com/dburka           dburka
28                  http://twitter.com/avh              avh
29                http://twitter.com/jhong            jhong
...                                    ...              ...
29389        https://twitter.com/jm_dejuan        jm_dejuan
29390    https://twitter.com/imbenclifford    imbenclifford
29391  https://twitter.com/DanielGolemanEI  DanielGolemanEI
29392      https://twitter.com/tbabapandey      tbabapandey
29393        https://twitter.com/andrewsel        andrewsel
29394         https://twitter.com/davekuhn         davekuhn
29395           https://twitter.com/mrksen           mrksen
29396       https://twitter.com/stuartross       stuartross
29397      https://twitter.com/amirelichai      amirelichai
29398     https://twitter.com/jjobs_tweets     jjobs_tweets
29399     https://twitter.com/felipeacosta     felipeacosta
29400   https://twitter.com/PaulKraaijvang   PaulKraaijvang
29401   https://twitter.com/PramodSaxena10   PramodSaxena10
29402    https://twitter.com/adittrivedi93    adittrivedi93
29403   https://twitter.com/lisasongsutton   lisasongsutton
29404     https://twitter.com/ThomasAlvord     ThomasAlvord
29405         https://twitter.com/speedman         speedman
29406        https://twitter.com/ginossarz        ginossarz
29407         https://twitter.com/ManuNuBa         ManuNuBa
29408                          http://www.             www.
29409           https://twitter.com/kmages           kmages
29410    https://twitter.com/ParasharAnmol    ParasharAnmol
29411         https://twitter.com/Asaf_ELS         Asaf_ELS
29412        https://twitter.com/mrobilant        mrobilant
29413         https://twitter.com/Louiessc         Louiessc
29414            https://twitter.com/grove            grove
29415           https://twitter.com/kanfil           kanfil
29416        https://twitter.com/RuviKitov        RuviKitov
29417          https://twitter.com/krymski          krymski
29418     https://twitter.com/Jeff_Marsden     Jeff_Marsden

[29419 rows x 2 columns]

In [22]:
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth)

In [38]:
def getFollowerCount(handle):
    try:
        print "bhjsdjhsdvhjg"
        results = api.get_user(handle)
        return results
        #return results.followers_count
    except:
        return None

In [44]:
twitterLinks.url[1]

'mpclark3'

In [66]:
def getFilteredUserData(x):
    if x != None:
        return {
            'created_at': x.created_at,
            'favourites_count' : x.favourites_count,
            'followers_count': x.followers_count,
            'friends_count': x.friends_count,
            'listed_count': x.listed_count,
            'location': x.location,
            'statuses_count': x.statuses_count
        }
    else:
        return None

In [57]:
def getUserData(handle):
    try:
        return api.get_user(handle)
    except:
        return None

In [58]:
unfilteredUserData = twitterLinks.handle[:1].map(lambda x: getUserData(x))

In [67]:
print map(getFilteredUserData, unfilteredUserData)

[{'favourites_count': 292, 'friends_count': 941, 'created_at': datetime.datetime(2009, 2, 13, 4, 16, 12), 'followers_count': 40115, 'location': u'', 'statuses_count': 1344, 'listed_count': 1170}]

In [68]:
unfilteredUserData = twitterLinks.handle[:30].map(lambda x: getUserData(x))

In [69]:
filteredUserData = map(getFilteredUserData, unfilteredUserData)

In [70]:
filteredUserData

[{'created_at': datetime.datetime(2009, 2, 13, 4, 16, 12),
  'favourites_count': 292,
  'followers_count': 40115,
  'friends_count': 941,
  'listed_count': 1170,
  'location': u'',
  'statuses_count': 1344},
 {'created_at': datetime.datetime(2008, 9, 2, 19, 10, 48),
  'favourites_count': 13,
  'followers_count': 927,
  'friends_count': 863,
  'listed_count': 19,
  'location': u'Denver, CO',
  'statuses_count': 1631},
 {'created_at': datetime.datetime(2007, 6, 6, 5, 47, 5),
  'favourites_count': 14648,
  'followers_count': 26082,
  'friends_count': 1511,
  'listed_count': 1214,
  'location': u'Manhattan Beach, CA',
  'statuses_count': 24462},
 None,
 {'created_at': datetime.datetime(2009, 4, 1, 3, 20, 5),
  'favourites_count': 359,
  'followers_count': 15907,
  'friends_count': 172,
  'listed_count': 404,
  'location': u'LA, NY, SF',
  'statuses_count': 3106},
 {'created_at': datetime.datetime(2007, 1, 31, 4, 42, 11),
  'favourites_count': 8058,
  'followers_count': 27316,
  'friends_count': 1403,
  'listed_count': 1448,
  'location': u'',
  'statuses_count': 19903},
 {'created_at': datetime.datetime(2006, 3, 21, 20, 51, 43),
  'favourites_count': 2905,
  'followers_count': 2909758,
  'friends_count': 704,
  'listed_count': 21331,
  'location': u'San Francisco, CA',
  'statuses_count': 6377},
 {'created_at': datetime.datetime(2007, 4, 6, 4, 21, 41),
  'favourites_count': 122,
  'followers_count': 4145,
  'friends_count': 403,
  'listed_count': 275,
  'location': u'San Francisco, CA',
  'statuses_count': 984},
 {'created_at': datetime.datetime(2007, 2, 3, 2, 41, 31),
  'favourites_count': 102,
  'followers_count': 527907,
  'friends_count': 415,
  'listed_count': 4239,
  'location': u'Honolulu, HI',
  'statuses_count': 7511},
 {'created_at': datetime.datetime(2008, 1, 29, 18, 24, 6),
  'favourites_count': 20,
  'followers_count': 230,
  'friends_count': 271,
  'listed_count': 14,
  'location': u'Alameda, CA',
  'statuses_count': 539},
 {'created_at': datetime.datetime(2008, 11, 26, 19, 20, 24),
  'favourites_count': 3433,
  'followers_count': 5516,
  'friends_count': 1817,
  'listed_count': 557,
  'location': u'San Francisco',
  'statuses_count': 5842},
 {'created_at': datetime.datetime(2008, 4, 8, 0, 30, 58),
  'favourites_count': 216,
  'followers_count': 3828,
  'friends_count': 553,
  'listed_count': 141,
  'location': u'San Francisco, CA',
  'statuses_count': 3155},
 {'created_at': datetime.datetime(2007, 1, 28, 18, 45, 59),
  'favourites_count': 1863,
  'followers_count': 41120,
  'friends_count': 668,
  'listed_count': 1878,
  'location': u'Orlando, FL',
  'statuses_count': 18380},
 {'created_at': datetime.datetime(2006, 8, 5, 23, 31, 27),
  'favourites_count': 51742,
  'followers_count': 275950,
  'friends_count': 26928,
  'listed_count': 13042,
  'location': u'94123',
  'statuses_count': 78110},
 {'created_at': datetime.datetime(2008, 4, 14, 18, 29, 55),
  'favourites_count': 13,
  'followers_count': 4693,
  'friends_count': 98,
  'listed_count': 310,
  'location': u'Here',
  'statuses_count': 1714},
 {'created_at': datetime.datetime(2007, 4, 29, 14, 19, 18),
  'favourites_count': 22,
  'followers_count': 1019,
  'friends_count': 245,
  'listed_count': 80,
  'location': u'',
  'statuses_count': 1465},
 {'created_at': datetime.datetime(2007, 4, 20, 18, 20, 47),
  'favourites_count': 2543,
  'followers_count': 2143,
  'friends_count': 205,
  'listed_count': 167,
  'location': u'',
  'statuses_count': 5125},
 {'created_at': datetime.datetime(2006, 12, 15, 22, 30, 27),
  'favourites_count': 5591,
  'followers_count': 17207,
  'friends_count': 574,
  'listed_count': 1077,
  'location': u'Palo Alto, CA',
  'statuses_count': 8484},
 {'created_at': datetime.datetime(2008, 5, 12, 20, 12, 9),
  'favourites_count': 195,
  'followers_count': 677904,
  'friends_count': 1251,
  'listed_count': 7324,
  'location': u'San Francisco, CA, USA',
  'statuses_count': 709},
 {'created_at': datetime.datetime(2007, 4, 13, 5, 47, 2),
  'favourites_count': 13,
  'followers_count': 4171,
  'friends_count': 90,
  'listed_count': 135,
  'location': u'San Francisco, CA',
  'statuses_count': 50},
 {'created_at': datetime.datetime(2007, 3, 11, 6, 4, 56),
  'favourites_count': 117,
  'followers_count': 4326,
  'friends_count': 120,
  'listed_count': 120,
  'location': u'iPhone: 37.771996,-122.431396',
  'statuses_count': 547},
 {'created_at': datetime.datetime(2007, 4, 3, 18, 52, 25),
  'favourites_count': 21,
  'followers_count': 2776,
  'friends_count': 118,
  'listed_count': 97,
  'location': u'SF',
  'statuses_count': 85},
 {'created_at': datetime.datetime(2009, 2, 25, 17, 31, 57),
  'favourites_count': 2538,
  'followers_count': 31031,
  'friends_count': 1046,
  'listed_count': 301,
  'location': u'San Francisco',
  'statuses_count': 13163},
 {'created_at': datetime.datetime(2008, 4, 5, 19, 24, 50),
  'favourites_count': 852,
  'followers_count': 5818,
  'friends_count': 410,
  'listed_count': 317,
  'location': u'San Francisco, CA',
  'statuses_count': 61},
 {'created_at': datetime.datetime(2010, 2, 24, 5, 31, 15),
  'favourites_count': 587,
  'followers_count': 24650,
  'friends_count': 53,
  'listed_count': 840,
  'location': u'',
  'statuses_count': 544},
 {'created_at': datetime.datetime(2008, 4, 28, 20, 53, 59),
  'favourites_count': 30,
  'followers_count': 453,
  'friends_count': 161,
  'listed_count': 36,
  'location': u'SF Bay Area',
  'statuses_count': 1262},
 {'created_at': datetime.datetime(2009, 8, 21, 13, 13, 47),
  'favourites_count': 2514,
  'followers_count': 13106,
  'friends_count': 5769,
  'listed_count': 588,
  'location': u'Berlin & New York',
  'statuses_count': 4149},
 {'created_at': datetime.datetime(2007, 1, 15, 15, 22, 14),
  'favourites_count': 13767,
  'followers_count': 41270,
  'friends_count': 491,
  'listed_count': 2523,
  'location': u'Brooklyn, NY',
  'statuses_count': 6220},
 {'created_at': datetime.datetime(2007, 11, 7, 5, 3, 15),
  'favourites_count': 495,
  'followers_count': 2757,
  'friends_count': 554,
  'listed_count': 168,
  'location': u'Menlo Park, California',
  'statuses_count': 2083},
 {'created_at': datetime.datetime(2007, 3, 13, 1, 15, 42),
  'favourites_count': 1125,
  'followers_count': 12902,
  'friends_count': 188,
  'listed_count': 562,
  'location': u'',
  'statuses_count': 2186}]

In [83]:
twitterLinksSubset = twitterLinks[:30]

In [86]:
twitterLinksSubset['favourites_count'] = map(lambda x: None if x == None else x['favourites_count'], filteredUserData)

/Users/kushasharma/anaconda/envs/hiveminds/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [88]:
twitterLinksSubset['followers_count'] = map(lambda x: None if x == None else x['followers_count'], filteredUserData)
twitterLinksSubset['friends_count'] = map(lambda x: None if x == None else x['friends_count'], filteredUserData)
twitterLinksSubset['listed_count'] = map(lambda x: None if x == None else x['listed_count'], filteredUserData)
twitterLinksSubset['location'] = map(lambda x: None if x == None else x['location'], filteredUserData)
twitterLinksSubset['statuses_count'] = map(lambda x: None if x == None else x['statuses_count'], filteredUserData)

/Users/kushasharma/anaconda/envs/hiveminds/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/Users/kushasharma/anaconda/envs/hiveminds/lib/python2.7/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
/Users/kushasharma/anaconda/envs/hiveminds/lib/python2.7/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/Users/kushasharma/anaconda/envs/hiveminds/lib/python2.7/site-packages/ipykernel/__main__.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/kushasharma/anaconda/envs/hiveminds/lib/python2.7/site-packages/ipykernel/__main__.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [89]:
twitterLinksSubset

,url,handle,created_at,favourites_count,followers_count,friends_count,listed_count,location,statuses_count
0,https://twitter.com/chrishughes,chrishughes,2009-02-13 04:16:12,292.0,40115.0,941.0,1170.0,,1344.0
1,http://twitter.com/mpclark3,mpclark3,2008-09-02 19:10:48,13.0,927.0,863.0,19.0,"Denver, CO",1631.0
2,http://twitter.com/peterpham,peterpham,2007-06-06 05:47:05,14648.0,26082.0,1511.0,1214.0,"Manhattan Beach, CA",24462.0
3,http://twitter.com/bigchiefalice,bigchiefalice,NaT,NaN,NaN,NaN,NaN,None,NaN
4,http://twitter.com/jason_rubin,jason_rubin,2009-04-01 03:20:05,359.0,15907.0,172.0,404.0,"LA, NY, SF",3106.0
5,http://twitter.com/gmc,gmc,2007-01-31 04:42:11,8058.0,27316.0,1403.0,1448.0,,19903.0
6,http://twitter.com/biz,biz,2006-03-21 20:51:43,2905.0,2909758.0,704.0,21331.0,"San Francisco, CA",6377.0
7,http://twitter.com/tripadler,tripadler,2007-04-06 04:21:41,122.0,4145.0,403.0,275.0,"San Francisco, CA",984.0
8,https://twitter.com/pierre,pierre,2007-02-03 02:41:31,102.0,527907.0,415.0,4239.0,"Honolulu, HI",7511.0
9,https://twitter.com/swamus,swamus,2008-01-29 18:24:06,20.0,230.0,271.0,14.0,"Alameda, CA",539.0
10,http://twitter.com/barneyp,barneyp,2008-11-26 19:20:24,3433.0,5516.0,1817.0,557.0,San Francisco,5842.0
11,http://twitter.com/thione,thione,2008-04-08 00:30:58,216.0,3828.0,553.0,141.0,"San Francisco, CA",3155.0
12,http://twitter.com/tedmurphy,tedmurphy,2007-01-28 18:45:59,1863.0,41120.0,668.0,1878.0,"Orlando, FL",18380.0
13,http://twitter.com/Jason,Jason,2006-08-05 23:31:27,51742.0,275950.0,26928.0,13042.0,94123,78110.0
14,http://twitter.com/todddowl,todddowl,2008-04-14 18:29:55,13.0,4693.0,98.0,310.0,Here,1714.0
15,http://twitter.com/sanity,sanity,2007-04-29 14:19:18,22.0,1019.0,245.0,80.0,,1465.0
16,http://twitter.com/aldamiz,aldamiz,2007-04-20 18:20:47,2543.0,2143.0,205.0,167.0,,5125.0
17,http://twitter.com/ginab,ginab,2006-12-15 22:30:27,5591.0,17207.0,574.0,1077.0,"Palo Alto, CA",8484.0
18,http://twitter.com/Chad_Hurley,Chad_Hurley,2008-05-12 20:12:09,195.0,677904.0,1251.0,7324.0,"San Francisco, CA, USA",709.0
19,http://twitter.com/stevechen,stevechen,2007-04-13 05:47:02,13.0,4171.0,90.0,135.0,"San Francisco, CA",50.0
20,http://twitter.com/eshear,eshear,2007-03-11 06:04:56,117.0,4326.0,120.0,120.0,"iPhone: 37.771996,-122.431396",547.0
21,https://twitter.com/kvogt,kvogt,2007-04-03 18:52:25,21.0,2776.0,118.0,97.0,SF,85.0
22,http://twitter.com/bhunstable,bhunstable,2009-02-25 17:31:57,2538.0,31031.0,1046.0,301.0,San Francisco,13163.0
23,http://twitter.com/cwalker123,cwalker123,2008-04-05 19:24:50,852.0,5818.0,410.0,317.0,"San Francisco, CA",61.0
24,https://twitter.com/jesslivingston,jesslivingston,2010-02-24 05:31:15,587.0,24650.0,53.0,840.0,,544.0
25,http://twitter.com/blakewilliams,blakewilliams,2008-04-28 20:53:59,30.0,453.0,161.0,36.0,SF Bay Area,1262.0
26,http://twitter.com/betashop,betashop,2009-08-21 13:13:47,2514.0,13106.0,5769.0,588.0,Berlin & New York,4149.0
27,http://twitter.com/dburka,dburka,2007-01-15 15:22:14,13767.0,41270.0,491.0,2523.0,"Brooklyn, NY",6220.0
28,http://twitter.com/avh,avh,2007-11-07 05:03:15,495.0,2757.0,554.0,168.0,"Menlo Park, California",2083.0
29,http://twitter.com/jhong,jhong,2007-03-13 01:15:42,1125.0,12902.0,188.0,562.0,,2186.0

In [92]:
twitterLinksSubset.to_csv('base_data/twitterData.csv')